# Build Steps
# 1. Make sure everything builds and runs
# 2. update version number in 'main.go' and 'download.sh'
# 3. commit changes
# 4. tag commit
# 5. delete 'dist' folder
# 6. export token
# 7. run goreleaser
# 8. push changes to GitHub
# 9. update release for latest commits
# 10. update AUR package

builds:
  - binary: gotop
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tgz
