# Build Steps
# 1. Make sure everything builds and runs
# 2. update version number in 'main.go' and 'download.sh'
# 3. commit changes
# 4. tag commit
# 5. export token
# 6. run goreleaser
# 7. delete 'dist' folder
# 8. push changes to GitHub
# 9. update AUR package

builds:
  - binary: gotop
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}{{ .Arm }}{{ end }}"
  replacements:
    arm64: arm8
  format: tgz
