[[constraint]]
  branch = "master"
  name = "github.com/cjbassi/termui"

[[constraint]]
  branch = "master"
  name = "github.com/docopt/docopt-go"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.2"

[prune]
  go-tests = true
  unused-packages = true
