[[constraint]]
  branch = "master"
  name = "github.com/cjbassi/termui"

[[constraint]]
  branch = "master"
  name = "github.com/docopt/docopt-go"

[[constraint]]
  branch = "master"
  name = "github.com/shirou/gopsutil"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/shirou/gopsutil"
  unused-packages = false
